$install_repos = <<SCRIPT
    rpm -Uvh http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm 
    rpm -Uvh http://dl.fedoraproject.org/pub/epel/5/i386/epel-release-5-4.noarch.rpm
    rpm -Uvh http://packages.erlang-solutions.com/erlang-solutions-1.0-1.noarch.rpm
    yum install erlang
SCRIPT

$install_chef = <<SCRIPT
if ! [ -d "/opt/chef" ];
then
    yum update
    yum install -y curl
    curl -L https://www.opscode.com/chef/install.sh | bash
fi
SCRIPT

Vagrant.configure("2") do |config|
   # config.vm.box = "opscode-ubuntu-13.04"
  # config.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-13.04_provisionerless.box"

  config.vm.box = "opscode-centos-6.4"
  config.vm.box_url = "https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--name", "sensu-centos"]
    vb.customize ["modifyvm", :id, "--memory", "1024"]
    vb.gui = true
  end

  config.vm.network :forwarded_port, guest: 3000, host: 3000
  config.vm.network :forwarded_port, guest: 80, host: 8081
  config.vm.network :forwarded_port, guest: 4567, host: 4567
  config.vm.network :forwarded_port, guest: 5671, host: 5671
  config.vm.network :forwarded_port, guest: 10524, host: 10525
  config.vm.hostname  = "sensu.mydomain.local"
  
  config.vm.network :forwarded_port, guest: 8080, host: 8081
  config.vm.provision :shell, :inline => "sudo su -"
  # config.vm.provision :shell, :inline => $install_repos
  config.vm.provision :shell, :inline => $install_chef

  config.vm.provision :chef_solo do |chef|
    chef.cookbooks_path = "cookbooks"
    chef.data_bags_path = "data_bags"
    chef.add_recipe "monitor::master"
    chef.add_recipe "monitor::redis"
    chef.add_recipe "monitor::rabbitmq"
  end
  config.vm.post_up_message = "Welcome Sam !! You have done a wonderful job today !!"
  config.vm.post_up_message = "NOT REALLY!, I AM JUST KIDDING - IT IS LONG WAY TO GO YET !!"

end
